### ISSUE TITLE
generateSourceMaps issue

### ISSUE THREAD

**Issue by gmp26** [WintonCentre/unspun#36]
On running the packager in `exp start -i` I'm now getting:
```
[exp] /Users/gmp26/clojure/unspun/node_modules/fbjs/lib/invariant.js:51
[exp]     throw error;
[exp]     ^
[exp] 
[exp] Invariant Violation: Minifying source code requires the `generateSourceMaps` option to be `true`
[exp]     at invariant (/Users/gmp26/clojure/unspun/node_modules/fbjs/lib/invariant.js:44:15)
[exp]     at makeTransformParams (/Users/gmp26/clojure/unspun/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:24:3)
[exp]     at transformCode (/Users/gmp26/clojure/unspun/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:89:18)
[exp]     at exports.transformAndExtractDependencies (/Users/gmp26/clojure/unspun/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:163:3)
[exp]     at handle (/Users/gmp26/clojure/unspun/node_modules/worker-farm/lib/child/index.js:41:8)
[exp]     at process.<anonymous> (/Users/gmp26/clojure/unspun/node_modules/worker-farm/lib/child/index.js:47:3)
[exp]     at emitTwo (events.js:106:13)
[exp]     at process.emit (events.js:191:7)
[exp]     at process.nextTick (internal/child_process.js:752:12)
[exp]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[exp] /Users/gmp26/clojure/unspun/node_modules/fbjs/lib/invariant.js:51
[exp]     throw error;
[exp]     ^
```

**Comment by gmp26** [comment]
Here's one lead:
https://github.com/expo/expo-docs/search?utf8=%E2%9C%93&q=SourceMaps&type=

**Comment by gmp26** [comment]
Here's one lead: 
https://github.com/expo/expo-docs/search?utf8=%E2%9C%93&q=SourceMaps&type=

**Comment by gmp26** [comment]
transient bug due to compile error
